jump_y_speed = 10.0

[wheel]
torque_multiplier = -1.6
angular_damping = 0.8
linear_damping = 0.0

[tube]
torque_multiplier = 0.004
angular_damping = 10.0
linear_damping = 0.0
mass = 0.01
length = 1.8

[camera]
playing_scale_divisor = 24.0

[torso]
width = 2.0
height = 1.5
sprite_height = 1.5
sprite_width = 2.2
death_force = 2.0
mass = 0.004
gravity_scale = 0.125

[head]
x = 0.0
y = 1.42
width = 1.5
height = 1.5

[eyes]
x = 0.0
y = 0.20
width = 0.9
height = 0.6

[arms]
length = 1.3
width = 0.5
angular_damping = 2.0
detach_force = 2.0
mass = 0.001
left.socket.point = { x = -0.9, y = 0.4 }
right.socket.point = { x = 0.9, y = 0.4 }

[debug]
physics = false

[editor]
camera_speed = 1000.0

[background]
# scale_x = 40.0
# scale_y = 40.0
scale_x = 20.0
scale_y = 20.0

[wall]
scale_x = 8.0
scale_y = 8.0
